apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: nkorydkxe-go 
  janus-idp.io/tekton: nkorydkxe-go
  backstage.io/kubernetes-id: nkorydkxe-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nkorydkxe-go
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml